### ISSUE TITLE
Target SDK level

### ISSUE THREAD

**Issue by Moetto** [cluo29/HMS_ACP_UI_Test#1]
Project is right now targeted on SDK 23 (Android 6.0). Should lower it to for perhaps to 19 (Android 4.4) to achieve large enough user space.

**Comment by cluo29** [comment]
It doesn't matter. Minimum is 10

**Comment by Moetto** [comment]
Okay, my bad. Didn't notice minimum level at glance as I was debugging why the app crashes constantly. I'll keep looking for another reason.
